id = "carve"
name = "Carve"
description = "Syntax highlighting for Carve, a post-Markdown lightweight markup language"
version = "0.1.1"
schema_version = 1
authors = ["Mark Scherer <dereuromark@users.noreply.github.com>"]
repository = "https://github.com/markup-carve/zed-carve"
themes = []
icon_themes = []
languages = ["languages/carve"]
snippets = ["./snippets/carve.json"]
capabilities = []

[grammars.carve]
repository = "https://github.com/markup-carve/tree-sitter-carve"
rev = "17362de88d2c3177e7c6b4d5f83841f38a42ae4d"

[language_servers.carve-lsp]
name = "Carve LSP"
languages = ["Carve"]
