id = "carve"
name = "Carve"
description = "Syntax highlighting for Carve, a lightweight markup language for documents and the web"
version = "0.1.4"
schema_version = 1
authors = ["Mark Scherer <dereuromark@users.noreply.github.com>"]
repository = "https://github.com/markup-carve/zed-carve"
themes = []
icon_themes = []
languages = ["languages/carve"]
snippets = ["./snippets/carve.json"]
capabilities = []

[grammars.carve]
repository = "https://github.com/markup-carve/tree-sitter-carve"
rev = "3d683213b504027ec28ea4e976978b96bf280b45"

[language_servers.carve-lsp]
name = "Carve LSP"
languages = ["Carve"]
