id = "carve"
name = "Carve"
description = "Syntax highlighting for Carve, a post-Markdown lightweight markup language"
version = "0.1.3"
schema_version = 1
authors = ["Mark Scherer <dereuromark@users.noreply.github.com>"]
repository = "https://github.com/markup-carve/zed-carve"
themes = []
icon_themes = []
languages = ["languages/carve"]
snippets = ["./snippets/carve.json"]
capabilities = []

[grammars.carve]
repository = "https://github.com/markup-carve/tree-sitter-carve"
rev = "9323ff5f9d87b20372fc3f4f9052fed67dd176ff"

[language_servers.carve-lsp]
name = "Carve LSP"
languages = ["Carve"]
